server {
    listen 80;
    server_name _;
    charset utf-8;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        try_files /index.html =404;
    }

    location = /debug {
        try_files /debug.html =404;
    }

    location = /lines {
        proxy_pass http://postgrest:3000/rpc/strange_roads_bbox;
        proxy_set_header Host $host;
    }

    location = /api/lines {
        proxy_pass http://postgrest:3000/rpc/strange_roads_bbox;
        proxy_set_header Host $host;
    }
}
